//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORIGIN_ATM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta_Usuario()
        {
            this.Operacion1 = new HashSet<Operacion>();
        }
    
        public int ID_Cuenta { get; set; }
        public string Numero_Cuenta { get; set; }
        public int Estado_Cuenta { get; set; }
        public string PIN_Cuenta { get; set; }
        public decimal Balance { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> ID_UltimaOperacion { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento { get; set; }
    
        public virtual Operacion Operacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacion> Operacion1 { get; set; }
    }
}
