//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORIGIN_ATM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operacion()
        {
            this.Cuenta_Usuario = new HashSet<Cuenta_Usuario>();
        }
    
        public int ID_Operacion { get; set; }
        public int ID_Cuenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta_Usuario> Cuenta_Usuario { get; set; }
        public virtual Cuenta_Usuario Cuenta_Usuario1 { get; set; }
    }
}
